### ISSUE TITLE
Integrate Hazard-Hunter app

### ISSUE THREAD

**Issue by web-apps-lab** [TristanCacqueray/haskell-butler#7]
Hi,

I'd like to discuss of the update the integrated MineSweeper app to Hazard-Hunter. If you are agree with that update then I'd like to propose like a plan. My proposal plan is in two step:

1. Migrate HH as a standalone repository/App/Package that fully relies on haskell-butler as engine (https://github.com/web-apps-lab/takoyaki/issues/1)
2. Add a build dependency in haskell-butler to that new HH Package and wire it to make the app available in the Butler Desktop app. The dependency could by distributed in form a git sub module to ease integration.

**Comment by TristanCacqueray** [comment]
Hi, thank you for opening this issue.

The current API is getting more and more stable. I think the next steps are:

- [ ] Move the `ButlerDemos` and `Butler.App.*` module to dedicated projects.
- [ ] Expose an easy to use API, as the one defined in https://github.com/TristanCacqueray/haskell-butler/blob/f955a3a59da27633f273f00c2dd26a519a749049/src/ButlerDemos.hs#L73-L76
- [ ] Create the `butler-desktop` project to integrate the existing apps.

In the future, I'd like to investigate how to load a prebuilt app into a running system, but for now we'll have to use build-depends.

**Comment by TristanCacqueray** [comment]
Moving the desktop demo is presently not possible, without losing the `ghcid` powered workflow. See https://github.com/haskell/cabal/issues/8491 .
Otherwise I think this issue is fixed, otherwise please re-open.
